"use strict";

const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const postsRoot = path.join(root, "content", "posts");
const siteDataPath = path.join(root, "content", "site-data.json");
const outputPath = path.join(root, "assets", "data.js");
const requiredFields = ["title", "date", "tags", "excerpt"];

function parsePost(filePath) {
  const source = fs.readFileSync(filePath, "utf8").replace(/\r\n?/g, "\n");
  if (!source.startsWith("---\n")) throw new Error(`${filePath}: 缺少 Markdown front matter`);
  const boundary = source.indexOf("\n---\n", 4);
  if (boundary < 0) throw new Error(`${filePath}: front matter 未正确结束`);

  const metadata = {};
  source.slice(4, boundary).split("\n").filter(Boolean).forEach((line) => {
    const separator = line.indexOf(":");
    if (separator < 1) throw new Error(`${filePath}: 无法解析元数据行 ${line}`);
    const key = line.slice(0, separator).trim();
    const rawValue = line.slice(separator + 1).trim();
    try {
      metadata[key] = JSON.parse(rawValue);
    } catch (error) {
      throw new Error(`${filePath}: ${key} 必须使用 JSON 格式`, { cause: error });
    }
  });

  const actualFields = Object.keys(metadata).sort();
  assertEqual(actualFields, [...requiredFields].sort(), `${filePath}: 元数据字段必须为 ${requiredFields.join(", ")}`);
  if (typeof metadata.title !== "string" || !metadata.title.trim()) throw new Error(`${filePath}: title 不能为空`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(metadata.date)) throw new Error(`${filePath}: date 必须为 YYYY-MM-DD`);
  if (!Array.isArray(metadata.tags) || metadata.tags.some((tag) => typeof tag !== "string" || !tag.trim())) {
    throw new Error(`${filePath}: tags 必须为非空字符串数组`);
  }
  if (typeof metadata.excerpt !== "string") throw new Error(`${filePath}: excerpt 必须为字符串`);

  const content = source.slice(boundary + 5).trimEnd();
  if (!content) throw new Error(`${filePath}: 正文不能为空`);
  return { ...metadata, content };
}

function assertEqual(actual, expected, message) {
  if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(message);
}

function buildOutput() {
  const siteData = JSON.parse(fs.readFileSync(siteDataPath, "utf8"));
  if (Object.prototype.hasOwnProperty.call(siteData, "posts")) {
    throw new Error("content/site-data.json 不应包含 posts；文章来自 content/posts/*.md");
  }
  const posts = fs.readdirSync(postsRoot)
    .filter((name) => name.endsWith(".md"))
    .map((name) => parsePost(path.join(postsRoot, name)))
    .sort((left, right) => right.date.localeCompare(left.date));
  if (!posts.length) throw new Error("content/posts 中没有 Markdown 文章");

  return `// Generated by scripts/build-content.js. Edit content/site-data.json and content/posts/*.md instead.\nconst SITE_DATA = ${JSON.stringify({ ...siteData, posts }, null, 2)};\n`;
}

function main() {
  const output = buildOutput();
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8").replace(/\r\n?/g, "\n") : "";
    if (current !== output) {
      console.error("assets/data.js 与内容源不同步，请运行：node scripts/build-content.js");
      process.exitCode = 1;
    }
    return;
  }
  fs.writeFileSync(outputPath, output);
  console.log(`已生成 ${path.relative(root, outputPath)}`);
}

if (require.main === module) main();

module.exports = { buildOutput, parsePost };
