"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const test = require("node:test");
const { parsePost } = require("../scripts/build-content.js");

const root = path.resolve(__dirname, "..");

test("six posts live as independent Markdown source files", () => {
  const postsRoot = path.join(root, "content", "posts");
  assert.equal(fs.existsSync(postsRoot), true, "content/posts must exist");
  const files = fs.readdirSync(postsRoot).filter((name) => name.endsWith(".md"));
  assert.equal(files.length, 6);
  for (const file of files) {
    const post = parsePost(path.join(postsRoot, file));
    assert.match(post.date, /^\d{4}-\d{2}-\d{2}$/);
    assert.ok(post.title.length > 0);
    assert.ok(post.tags.length > 0);
    assert.ok(post.content.length > 0);
  }
});

test("site data source excludes generated posts", () => {
  const sourcePath = path.join(root, "content", "site-data.json");
  assert.equal(fs.existsSync(sourcePath), true, "content/site-data.json must exist");
  const source = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
  assert.equal("posts" in source, false);
});

test("content generator validates the committed browser data", () => {
  const result = spawnSync(process.execPath, ["scripts/build-content.js", "--check"], {
    cwd: root,
    encoding: "utf8",
  });
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.match(fs.readFileSync(path.join(root, "assets", "data.js"), "utf8"), /Generated by scripts\/build-content\.js/);
});

test("deployment checks content generation before assembling assets", () => {
  const workflow = fs.readFileSync(path.join(root, ".github", "workflows", "build.yml"), "utf8");
  const checkAt = workflow.indexOf("node scripts/build-content.js --check");
  const copyAt = workflow.indexOf("Copy-Item ./assets");
  assert.ok(checkAt >= 0, "workflow must run the content check");
  assert.ok(copyAt > checkAt, "content check must happen before assets are copied");
});
